/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package s3t3e1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
	
		Menu menu = new Menu();
		menu.start();
	}

}
