/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package s3t3e1;

import s3t3e1.GardenShop.infrastructure.cli.Menu;

public class App {
   
    public static void main(String[] args) {
	
		Menu menu = new Menu();
		menu.start();
	}

}
